width: 1200
height: 600
font-size: 14
font-color: "#FFFFFF"
background-color: "#FFFFFF"
color-1: "#0096FF"
color-2: "#2AC2C4"
color-3: "#FF2400"
color-4: "#FF8A00"
color-5: "#FCFF00"
color-6: "#A868E3"
color-7: "#FC48D4"